name: Create release

on:
  push:
    branches:
      - 'master' 

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04      
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get project version from .csproj
        id: version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ./src/EventLog/EventLog.csproj)
          echo "Project version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title "$VERSION" \
              --latest