name: Create release and publish NuGet

on:
  push:
    branches:
      - 'master' 

permissions:
  contents: write
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
    
jobs:
  tag_and_push:
    name: Create and push release tag
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Alex Holenko"
          git config --global user.email "cat-begemot@live.com"

      - name: Get project version from .csproj
        id: version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ./src/EventLog/EventLog.csproj)
          echo "Project version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Fetch the latest changes from the remote repository
        run: |
          git fetch --all
          
      - name: Create a new tag
        run: |
          NEW_TAG="v$VERSION"
          git checkout master
          git pull origin master
          git tag $NEW_TAG
          echo "Tag created: $NEW_TAG"

      - name: Push tag to remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin $NEW_TAG
          
  release:
    name: Create release
    runs-on: ubuntu-24.04
    needs: tag_and_push
    if: success()
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get latest tag from master
        run: |
          git fetch --tags
          tag=$(git describe --tags --abbrev=0 origin/master)
          echo "Latest tag on master: $tag"
      
      - name: Create GitHub release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              --generate-notes \
              --verify-tag \
              --latest
  
  create_nuget:
    name: Create NuGet
    runs-on: ubuntu-24.04
    needs: release
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Pack
        shell: pwsh
        run: dotnet pack .\src\EventLog --configuration Release --output ${{ env.NuGetDirectory }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg
          
  deploy:
    name: Deploy NuGet
    runs-on: ubuntu-24.04
    needs: create_nuget
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Publish NuGet package
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }