name: Create release by tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: EventLog release
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/') && github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              --verify-tag \
              --latest