name: Create release and publish NuGet

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  setup_env_vars:
    name: Set environment variables
    runs-on: ubuntu-latest
    outputs:
      runner_image: ${{ steps.runner_image.outputs.runner_image }}
    steps:
      - name: Set runner image
        id: runner_image
        run: echo "runner_image=ubuntu-latest" >> $GITHUB_OUTPUT
        
  run_test:
    name: Run tests
    needs: setup_env_vars
    if: success()
    runs-on: ${{ needs.setup_env_vars.outputs.runner_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Run tests
        shell: pwsh
        run: dotnet test --configuration Release .\src\EventLog.UnitTests
  
  check_version:
    name: Check project version
    needs: setup_env_vars
    if: ${{ success() && github.event.repository.fork == false }}
    runs-on: ${{ needs.setup_env_vars.outputs.runner_image }}
    outputs:
      is_valid: ${{ steps.compare_versions.outputs.is_valid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get project version from .csproj
        uses: ./.github/actions/get-project-version

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag -l "v*" --sort=-v:refname | head -n 1)
          echo "Latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Compare Strings
        id: compare_versions
        run: |
          GREATER_VERSION=$(printf "%s\n%s" "$VERSION" "${LATEST_TAG#v}" | sort -V | tail -n 1)
          if [[ "$VERSION" == "$GREATER_VERSION" && "$VERSION" != "${LATEST_TAG#v}" ]]; then
            echo "The new release version is v$VERSION"
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "The project version is not incremented"
            echo "is_valid=false" >> $GITHUB_OUTPUT
          fi
  
  tag_and_push:
    name: Create and push release tag
    needs: [run_test, check_version]
    if: ${{ success() && needs.check_version.outputs.is_valid == 'true' }}
    runs-on: ${{ needs.setup_env_vars.outputs.runner_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Get project version from .csproj
        uses: ./.github/actions/get-project-version

      - name: Fetch the latest changes from the remote repository
        run: |
          git fetch --tags

      - name: Create and push tag
        run: |
          NEW_TAG="v$VERSION"
          git tag $NEW_TAG
          echo "Tag created: $NEW_TAG"
          git push origin $NEW_TAG
  
  release:
    name: Create release
    runs-on: ${{ needs.setup_env_vars.outputs.runner_image }}
    needs: tag_and_push
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub release
        run: |
          git fetch --tags
          NEW_TAG=$(git describe --tags --abbrev=0 origin/master)
          echo "Latest tag on master: $NEW_TAG"
          gh release create $NEW_TAG \
              --repo="$GITHUB_REPOSITORY" \
              --title="${NEW_TAG#v}" \
              --generate-notes \
              --generate-notes \
              --verify-tag \
              --latest
  
  create_nuget:
    name: Create NuGet
    runs-on: ${{ needs.setup_env_vars.outputs.runner_image }}
    needs: tag_and_push
    if: success()
    env:
      NuGetDirectory: ${{ github.workspace}}/nuget
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Pack
        shell: pwsh
        run: dotnet pack .\src\EventLog --configuration Release --output ${{ env.NuGetDirectory }}

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg
  
  deploy:
    name: Deploy NuGet
    runs-on: ${{ needs.setup_env_vars.outputs.runner_image }}
    needs: create_nuget
    if: success()
    env:
      NuGetDirectory: ${{ github.workspace}}/nuget
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Publish NuGet package
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }